clear;clc;

numProblems = 28;
numRuns     = 25;  
for p = 1:numProblems
    problemHandle = str2func( sprintf('CEC2017_F%d', p) );
    
    parfor runIdx = 1:numRuns
        platemo( ...
          'algorithm', @AGEA, ...
          'problem',   problemHandle, ...
          'N',         100, ...
          'D',         30, ...
          'maxFE',     600000, ...
          'save',      2000, ...
          'metName',   {'Min_value'}, ...
          'run',       runIdx ...
        );
    end
end
